---
title: "Analysis report of melanoma scRNA-Seq data"
author: "Maria Schmidt"
affiliation: "IZBI, Interdisciplinary Centre for Bioinformatics, Leipzig University, Germany"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: false
link-citations: true
params:
  run: "s1_LE479_NM_T"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libraries and load data}
pacman::p_load(Seurat, tidyverse, ggplot2, pals)
source(here("src","seurat-functions.r"))

output_data_path <- file.path("output")
seurat_object <- load_seurat_object(data_set_name = params$run,  output_data_path = output_data_path)

seurat_colors <- scales::hue_pal()(length(table(seurat_object@meta.data[, "seurat_clusters"])))
seurat_cluster_data <- data.frame(
    table(seurat_object@meta.data[, "seurat_clusters"]),
    "color" = seurat_colors
)

celltype_colors <- pals::polychrome(length(table(seurat_object@meta.data[, "predicted.id.Cell_type"])))
names(celltype_colors) <- table(seurat_object@meta.data[, "predicted.id.Cell_type"]) %>% names()
celltype_cluster_data <- data.frame(
    table(seurat_object@meta.data[, "predicted.id.Cell_type"]),
    "color" = celltype_colors
)

```


# Preprocessing, data integration and dimension reduction

## Quality check

We checked quality of all 3 Samples and removed apoptotic cells and doublets, so that we filtered from 3772 to `r length(seurat_object$seurat_clusters)` cells. Filtering out low count cells was done by cellranger.

```{r, echo=FALSE,  fig.width = 12, fig.height = 5}
VlnPlot(seurat_object, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), group.by = "predicted.id.Cell_type", cols = celltype_colors)
# FeatureScatter(seurat_object, feature1 = "nCount_RNA", feature2 = "percent.mt", group.by = "predicted.id.Cell_type")
ggplot(seurat_object@meta.data) +
        geom_point(aes(x = nCount_RNA, y = nFeature_RNA, colour = percent.mt)) +
        scale_color_continuous() +
        theme_minimal()

```